### ISSUE TITLE
Problem with BUNDLER_VERSION export

### ISSUE THREAD

**Issue by selialkile** [ruby/setup-ruby#119] opened 2020-12-07 16:03 UTC
After the commit when you export the BUNDLER_VERSION, causes a bug with a bin/rubocop, because they try to look a bundle using the BUNDLER_VERSION, but that version is incomplete and only has the main version:

![image](https://user-images.githubusercontent.com/717981/101374092-08eac280-38ae-11eb-9c99-f59dcb4e121e.png)

Commit:
 
https://github.com/ruby/setup-ruby/commit/30f5e2d4cd1b8bf01480423c9be9c5671a083aeb#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346

Screenshot:
![image](https://user-images.githubusercontent.com/717981/101373560-5e729f80-38ad-11eb-8a95-44dd7202a5dd.png)

**Comment by MSP-Greg** [comment] 2020-12-07 16:14
Setting BUNDLER_VERSION has also caused a failure in ruby/ruby CI.  It breaks a few Bundler tests in the RubyGems tests.

It was difficult to locate, as the MinGW build is the only workflow using setup-ruby that also runs test-all.

At the same time, there were failures caused by expired certs, which stopped all CI when installing bundled gems...

**Comment by eregon** [comment] 2020-12-07 16:47
Sorry about that.
I think we should be able to set `BUNDLER_VERSON` just for the commands that need it inside the action, and not for other steps (later `bundle` commands will pick the right version from `Gemfile.lock` anyway).
PR https://github.com/ruby/setup-ruby/pull/118
@ojab Would you be interested to try to fix this?

**Comment by ojab** [comment] 2020-12-07 16:51
Sure, on it.

**Comment by ojab** [comment] 2020-12-07 17:35
https://github.com/ruby/setup-ruby/pull/120

**Comment by eregon** [comment] 2020-12-07 20:28
Fixed and released as https://github.com/ruby/setup-ruby/releases/tag/v1.57.1

**Closed by eregon** 2020-12-07 20:28 UTC
