### ISSUE TITLE
Psych 5.x fails to install

### ISSUE THREAD

**Issue by parkr** [ruby/setup-ruby#412] opened 2022-12-08 20:34 UTC
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### The workflow code or a link to the workflow file

```yaml
https://github.com/jekyll/jekyll-import/blob/master/.github/workflows/ci.yml
```

### Link to the log of a failed workflow job, or to a gist with the output

https://github.com/jekyll/jekyll-import/actions/runs/3638899470/jobs/6141644262

### The command and output of the failing step

```shell
- name: "Set up Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
  
  current directory:
  /home/runner/work/jekyll-import/jekyll-import/vendor/bundle/ruby/3.1.0/gems/psych-5.0.0/ext/psych
  /opt/hostedtoolcache/Ruby/3.1.3/x64/bin/ruby -I
  /opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/3.1.0 extconf.rb
  checking for yaml.h... no
  yaml.h not found
  *** extconf.rb failed ***
  Could not create Makefile due to some reason, probably lack of necessary
  libraries and/or headers.  Check the mkmf.log file for more details.  You may
  need configuration options.
```

### Any other notes?

[Psych 5.0](https://github.com/ruby/psych/releases/tag/v5.0.0) stopped bundling libyaml (https://github.com/ruby/psych/pull/541), so now `ruby/setup-ruby@v1` fails during `bundle install` since `yaml.h` is missing.

**Comment by eregon** [comment] 2022-12-08 20:42
Duplicate of https://github.com/ruby/setup-ruby/issues/409 and not a setup-ruby issue.

**Closed** 2022-12-08 20:42 UTC
