### ISSUE TITLE
cannot load such file -- bundler/gem_tasks with Ruby 2.3 and Bundler 2

### ISSUE THREAD

**Issue by anirbanmu** [ruby/setup-ruby#51] opened 2020-04-28 01:54 UTC
I've been using this action for a bit to test a gem for all ruby versions from 2.3 - 2.7. CI hadn't run on it for about a month, and I see now that the behavior of which bundler version is installed by default has changed. I am hitting this error on the ruby 2.3 tests with the latest version of this action which I did not with previous versions:

```
Run bundle exec rake spec
rake aborted!
LoadError: cannot load such file -- bundler/gem_tasks
/home/runner/work/str_metrics/str_metrics/Rakefile:3:in `require'
/home/runner/work/str_metrics/str_metrics/Rakefile:3:in `<top (required)>'
/home/runner/work/str_metrics/str_metrics/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/home/runner/.rubies/ruby-2.3.8/bin/bundle:22:in `load'
/home/runner/.rubies/ruby-2.3.8/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)
##[error]Process completed with exit code 1.
```

I am guessing it's to do with the action now by default installing bundler 2 where it was installing bundler 1 for older rubies before? Has anyone encountered this? Any pointers/ideas on how to fix would be greatly appreciated! Thank you.

EDIT: I figured out that if I add a `gem update --system` before my `bundle install` step, everything seems to run OK. This somehow implies a too old version of rubygems? I saw this after installing ruby2.3 using this action:
```
gem -v
> 2.5.2.3
gem update --system
gem -v
> 3.1.2
```

According to https://github.com/rubygems/rubygems#requirements rubygems 3 supports ruby 2.3 and greater. Is there any reason to not use rubygems 3 for my usecase where I'm only supporting rubies greater than 2.3, jruby & truffleruby? I've for now just added a `gem update --system` to my workflow to workaround this.

**Comment by MSP-Greg** [comment] 2020-04-28 03:05
You might try adding `bundler: none` as an action input.

**Comment by eregon** [comment] 2020-04-28 10:21
Thanks for the report, and sorry that it broke for you.
Indeed that behavior changed and if you want to always use bundler 1 (as before) you can do:
```yaml
with:
  bundler: 1
```

Updating RubyGems in CI (i.e., `gem update --system`) is something I would recommend against: https://eregon.me/blog/2020/01/13/a-migration-path-to-bundler2.html#the-rubygems-requirement-of-bundler-2

Could you share the URL of that CI run that failed? That way I could try to analyze it or reproduce it.

Maybe we should consider always using Bundler 1 on Ruby 2.3 (and not just on Ruby 2.2) if there are known bugs with that version of RubyGems + Bundler 2. We need to know better why it fails first though.

**Comment by anirbanmu** [comment] 2020-04-29 01:13
> You might try adding `bundler: none` as an action input.
@MSP-Greg so if I'm understanding [this](https://github.com/ruby/setup-ruby/blob/master/action.yml#L13) correctly, setting `none` just wouldn't install bundler at all or it would always keep the default bundler that shipped with ruby? (actually I'm not certain that all rubies come with bundler already or not... probably not)

@eregon thanks for heads up with upgrading RubyGems in CI. I mostly did that for a short term fix to get my CI green. Will definitely remove when I get this figured out. Here's a link to a failed CI run: https://github.com/anirbanmu/str_metrics/runs/624606645?check_suite_focus=true I'm also happy to modify my CI workflow on a branch on that repo I linked to help debug further into what may be issue, since perhaps the run I linked lacks enough information.

**Comment by MSP-Greg** [comment] 2020-04-29 01:33
@anirbanmu

I apologize, I didn't check the build code (in another repo), as I can't recall whether it installed a version of bundler in none was installed in the 'default' builds.

You stated that the action previously worked.  I believe that using `bundler: none` is the same as the previous code.

**Comment by eregon** [comment] 2020-04-29 09:29
`bundler: none` is not the same as previously.
Previously, Bundler 1 was pre-installed if there wasn't already a bundler in stdlib (2.6 has Bundler 1, 2.7+ has Bundler 2). So Bundler was installed on Ruby <= 2.5.

`bundler: 1` is the closest to previous behavior, except it will also use Bundler 1 on Ruby 2.7+ (instead of 2), which is good for consistency (e.g., basically needed if there is a Gemfile.lock BUNDLED WITH 1) and should work fine.

My recommendation is:
* Use the default, should work in most cases (but obviously here there is some bug preventing it to work which we need to figure out)
* Use `bundler: 1` if the default doesn't work or you specifically want Bundler 1.
* Use `bundler: none` if you never need Bundler. If you want to install bundler manually you could also use `none` but this is not advisable, inefficient and might break `-head` versions.

**Comment by eregon** [comment] 2020-04-29 09:35
I couldn't reproduce it locally with just:
```
chruby 2.3.8
gem install bundle
bundle install
bundle exec rake spec
```

But I can reproduce it with:
```
chruby 2.3.8
gem install bundle
bundle config --local path vendor/bundle
bundle install
bundle exec rake spec
```

That seems clearly a RubyGems or Bundler bug, I'll dig deeper.

**Comment by eregon** [comment] 2020-04-29 09:40
The problem is that $LOAD_PATH entry for Bundler's `lib` is incorrect with `path vendor/bundle`:
```
/home/eregon/tmp/str_metrics/lib
/home/eregon/tmp/extensions/x86_64-linux/2.3.0-static/str_metrics-0.1.1
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/rubocop-rspec-1.38.1/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/rubocop-performance-1.5.2/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/rubocop-0.81.0/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/unicode-display_width-1.7.0/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/ruby-progressbar-1.10.1/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/rspec-3.9.0/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/rspec-mocks-3.9.1/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/rspec-expectations-3.9.1/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.9.1/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/rspec-support-3.9.2/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/rexml-3.2.4/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/rainbow-3.0.0/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/pry-0.13.1/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/parser-2.7.1.1/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/parallel-1.19.1/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/method_source-1.0.0/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/jaro_winkler-1.5.4/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0-static/jaro_winkler-1.5.4
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/ffi-1.12.2/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0-static/ffi-1.12.2
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/diff-lcs-1.3/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/coderay-1.1.2/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/bundler-2.1.4/lib/gems/bundler-2.1.4/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/ast-2.4.0/lib
/home/eregon/tmp/str_metrics/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/site_ruby/2.3.0
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/site_ruby/2.3.0/x86_64-linux
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/site_ruby
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/vendor_ruby/2.3.0
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/vendor_ruby/2.3.0/x86_64-linux
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/vendor_ruby
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/2.3.0
```
compared to (without `path vendor/bundle`):
```
/home/eregon/tmp/str_metrics/lib
/home/eregon/tmp/extensions/x86_64-linux/2.3.0-static/str_metrics-0.1.1
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/rubocop-rspec-1.38.1/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/rubocop-performance-1.5.2/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/rubocop-0.81.0/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/unicode-display_width-1.7.0/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/ruby-progressbar-1.10.1/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/rspec-3.9.0/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/rspec-mocks-3.9.1/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.9.1/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/rspec-core-3.9.1/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/rspec-support-3.9.2/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/rexml-3.2.4/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/rainbow-3.0.0/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/pry-0.13.1/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/parser-2.7.1.1/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/parallel-1.19.1/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/method_source-1.0.0/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/jaro_winkler-1.5.4/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0-static/jaro_winkler-1.5.4
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/ffi-1.12.2/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0-static/ffi-1.12.2
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/diff-lcs-1.3/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/coderay-1.1.2/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/bundler-2.1.4/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/ast-2.4.0/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/rake-12.3.3/lib
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/site_ruby/2.3.0
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/site_ruby/2.3.0/x86_64-linux
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/site_ruby
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/vendor_ruby/2.3.0
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/vendor_ruby/2.3.0/x86_64-linux
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/vendor_ruby
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/2.3.0
/home/eregon/.rubies/ruby-2.3.8/lib/ruby/2.3.0/x86_64-linux
```

`/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/bundler-2.1.4/lib` is correct but `/home/eregon/.rubies/ruby-2.3.8/lib/ruby/gems/2.3.0/gems/bundler-2.1.4/lib/gems/bundler-2.1.4/lib` is obviously not and doesn't exist.

**Comment by eregon** [comment] 2020-04-29 10:09
I filed an issue to RubyGems/Bundler: https://github.com/rubygems/rubygems/issues/3570

**Comment by eregon** [comment] 2020-04-29 10:12
So another workaround beside `bundler: 1` for this is to not use `bundle config path vendor/bundle` and not cache gems, which is probably fine in your case since it takes like 10 seconds to `bundle install`.

**Comment by eregon** [comment] 2020-04-29 10:41
Another solution is to stop supporting Ruby 2.3 in your gem, it's EOL, does not compile on any recent system, uses an unsupported version of OpenSSL, etc as the README says:

> Note that Ruby ≤ 2.3 and the OpenSSL version it needs (1.0.2) are both end-of-life, which means Ruby ≤ 2.3 is unmaintained and considered insecure

**Comment by eregon** [comment] 2020-05-03 11:55
A good fix for this seems to be to wait for the Bundler 2.2 release: https://github.com/rubygems/rubygems/issues/3570

**Comment by anirbanmu** [comment] 2020-05-04 22:32
@eregon thanks for all the work tracking this and reporting this upstream. Really appreciate it. I will wait for that release! Thanks again!

**Comment by eregon** [comment] 2020-05-05 23:03
Note: this also affects Puma's CI: https://github.com/rubygems/rubygems/issues/3570#issuecomment-624348235

**Closed** 2020-06-06 11:19 UTC

**Comment by eregon** [comment] 2020-06-06 11:20
To workaround this issue, Bundler 1 will always be used on Ruby 2.3 (b04e5b8).
When the next Bundler 2 release goes out, we can use Bundler 2 again, but since Ruby 2.3 is quite old (and EOL) it might be best to stick to Bundler 1 on Ruby 2.3.
