### ISSUE TITLE
Failed on ```bundle install``` on "rake"

### ISSUE THREAD

**Issue by acearth** [ruby/setup-ruby#215] opened 2021-09-03 10:25 UTC
My action config
```
... ...
    build:
      runs-on: [self-hosted, linux]
      steps:
        - uses: actions/checkout@v2.1.1
        - uses: ruby/setup-ruby@v1.50.3
          with:
            bundler-cache: true
... ... 
```

My action runs on a self-hosted machine WITHOUT ruby. The action is failed on Run ruby/setup-ruby@v1.50.3

The log is 
```
Run ruby/setup-ruby@v1.50.3
Using 2.7.2 as input from file .ruby-version
Downloading Ruby
Extracting Ruby
Installing Bundler
bundle install
  /opt/hostedtoolcache/Ruby/2.7.2/x64/bin/bundle config --local path vendor/bundle
  Cache key: setup-ruby-toolcache-bundle-install-ubuntu-18.04-ruby-2.7.2-Gemfile
  /opt/hostedtoolcache/Ruby/2.7.2/x64/bin/bundle install --jobs 4
  Fetching gem metadata from http://manda.ariel-networks.com/gem/...
  Could not find gem 'rake (~> 10.0)' in rubygems repository
  http://manda.ariel-networks.com/gem/ or installed locally.
  Took   2.31 seconds
Error: The process '/opt/hostedtoolcache/Ruby/2.7.2/x64/bin/bundle' failed with exit code 7
```

My .ruby-version is 2.7.2

In my Gemfile and Gemfile.lock, no `rake` info.

**Comment by eregon** [comment] 2021-09-04 13:18
It seems you set a custom gem source, I guess that's probably what causes the failure here.
`http://manda.ariel-networks.com/` does not resolve publicly.
It seems a user error or network issue, not caused by this action, so I close this.

**Closed by eregon** 2021-09-04 13:18 UTC
