### ISSUE TITLE
ruby setup error due to hardcoded username 'runner'

### ISSUE THREAD

**Issue by aditya-enthu** [ruby/setup-ruby#322] opened 2022-04-30 19:23 UTC
https://github.com/ruby/setup-ruby/blob/eb938a806ed6dbfb36293b94ccb2afaf2d590c92/common.js#L131

As in above line, the user for macOS is runner which cannot be true in case of self-hosted runner.

Is there a way we can bypass this stage or correct it. Thank you in advance.

steps:
```
     - name: Setup Ruby 
        uses: ruby/setup-ruby@v1
        env:
          ImageOS: macos1015
        with:
          ruby-version: '2.6.8'
          bundler-cache: false
```

Error:

```
  ImageOS: macos1015
##[endgroup***
##[group***Modifying PATH
Entries removed from PATH to avoid conflicts with default Ruby:
  /usr/local/opt/ruby/bin
  /usr/local/opt/ruby/bin
Entries added to PATH to use selected Ruby:
  /Users/runner/hostedtoolcache/Ruby/2.6.8/x64/bin
##[endgroup***
##[error***Error: EACCES: permission denied, mkdir '/Users/runner'
```

Created user 'runner' but running job from other user end up in error too.

```
  ImageOS: macos1015
##[endgroup***
##[group***Modifying PATH
Entries removed from PATH to avoid conflicts with default Ruby:
  /usr/local/opt/ruby/bin
  /usr/local/opt/ruby/bin
Entries added to PATH to use selected Ruby:
  /Users/**runner**/hostedtoolcache/Ruby/2.6.8/x64/bin
##[endgroup***
##[error***Error: EACCES: permission denied, mkdir '/Users/runner/hostedtoolcache'
```

**Comment by MSP-Greg** [comment] 2022-04-30 20:23
@aditya-enthu

I believe the only MRI Rubies that are portable are Windows Rubies.  All other OS's have hard-coded paths in the build.

**Comment by eregon** [comment] 2022-05-01 09:54
It's documented: https://github.com/ruby/setup-ruby#using-self-hosted-runners
Also duplicate of https://github.com/ruby/setup-ruby/issues/296

> which cannot be true in case of self-hosted runner.

Why not?

**Closed by eregon** 2022-05-01 09:54 UTC
