### ISSUE TITLE
Action failing on ubuntu20

### ISSUE THREAD

**Issue by sebastianMagnaldi** [ruby/setup-ruby#471] opened 2023-03-01 15:03 UTC
Hey ! I'm using this action on a self-hosted runner that is running ubuntu 20.4

This is how i'm defining the action in the yml

```
    - name: Set up Ruby from .ruby-version file
      uses: ruby/setup-ruby@v1
      env:
        ImageOS: ubuntu20
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
```

Before i was using this config and it was working perfectly fine. But then with the deprecation of ubuntu18 i had to update to ubuntu20 and it started failing : 

```
    - name: Set up Ruby from .ruby-version file
      uses: ruby/setup-ruby@v1
      env:
        ImageOS: ubuntu18
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
```

This is the error that i'm getting: 

```
An error occurred while installing ffi (1.15.5), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.15.5' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  cocoapods was resolved to 1.11.3, which depends on
    cocoapods-core was resolved to 1.11.3, which depends on
      typhoeus was resolved to 1.4.0, which depends on
        ethon was resolved to 0.16.0, which depends on
          ffi


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/home/ubuntu/actions-runner/_work/mobile/mobile/vendor/bundle/ruby/2.7.0/gems/unf_ext-0.0.8.2/ext/unf_ext
/opt/hostedtoolcache/Ruby/2.7.5/x64/bin/ruby -I
/opt/hostedtoolcache/Ruby/2.7.5/x64/lib/ruby/2.7.0 -r
./siteconf20230301-3399463-gfdj6u.rb extconf.rb
checking for -lstdc++... yes
creating Makefile

current directory:
/home/ubuntu/actions-runner/_work/mobile/mobile/vendor/bundle/ruby/2.7.0/gems/unf_ext-0.0.8.2/ext/unf_ext
make "DESTDIR=" clean

current directory:
/home/ubuntu/actions-runner/_work/mobile/mobile/vendor/bundle/ruby/2.7.0/gems/unf_ext-0.0.8.2/ext/unf_ext
make "DESTDIR="
compiling unf.cc
linking shared-object unf_ext.so

current directory:
/home/ubuntu/actions-runner/_work/mobile/mobile/vendor/bundle/ruby/2.7.0/gems/unf_ext-0.0.8.2/ext/unf_ext
make "DESTDIR=" install
make: /usr/bin/mkdir: Command not found
make: *** [Makefile:202: .sitearchdir.time] Error 127

make install failed, exit code 2

Gem files will remain installed in
/home/ubuntu/actions-runner/_work/mobile/mobile/vendor/bundle/ruby/2.7.0/gems/unf_ext-0.0.8.2
for inspection.
Results logged to
/home/ubuntu/actions-runner/_work/mobile/mobile/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/unf_ext-0.0.8.2/gem_make.out

An error occurred while installing unf_ext (0.0.8.2), and Bundler cannot
continue.
Make sure that `gem install unf_ext -v '0.0.8.2' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  fastlane was resolved to 2.211.0, which depends on
    faraday-cookie_jar was resolved to 0.0.7, which depends on
      http-cookie was resolved to 1.0.5, which depends on
        domain_name was resolved to 0.5.20190701, which depends on
          unf was resolved to 0.1.4, which depends on
            unf_ext
Error: The process '/opt/hostedtoolcache/Ruby/2.7.5/x64/bin/bundle' failed with exit code 5
Run npm uninstall -g yarn
/home/ubuntu/actions-runner/_work/_temp/7672c0d7-59b2-4337-a810-c5a7332[808](https://github.com/healthstarconnectsllc/mobile/actions/runs/4304708192/jobs/7506111391#step:3:819)cb.sh: line 1: npm: command not found
Error: Process completed with exit code 127.
```
Also i've tried to remove the env configuration in the action as follows: 
```
    - name: Set up Ruby from .ruby-version file
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
```
but then i get : `ImageOS enviroment variable must be set` and i think that's because the runner doesn't have the ImageOS variable configured but before setting the ImageOS in the action configuration worked as a charm.

- i've tried invalidating the cache but same issue.
- i've tried running the action with the following config and it worked: 

```
    - name: Set up Ruby from .ruby-version file
      uses: ruby/setup-ruby@v1.138.0
      env:
        ImageOS: ubuntu18
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
```

**Comment by hsbt** [comment] 2023-03-01 23:47
> make: /usr/bin/mkdir: Command not found

see above error. You may need to symlink it with `/bin/mkdir`.

**Comment by eregon** [comment] 2023-03-02 13:19
Well, isn't it obvious that changing `ImageOS` but not actually changing the self-hosted runner to be based on Ubuntu 20.04 is not going to work?

Closing as invalid issue, you need to update your runner.

**Closed by eregon** 2023-03-02 13:19 UTC

**Comment by sebastianMagnaldi** [comment] 2023-03-02 13:25
My self hosted runner is on 20.04 as i said in the first line of the issue.

**Comment by eregon** [comment] 2023-03-02 13:28
Alright, then in that case it's what hsbt said above, and that's probably a problem of your self-hosted runner.

**Comment by eregon** [comment] 2023-03-02 13:31
It seems unlikely you are using Ubuntu 20.04, even the Docker image has it:
```
$ podman run --rm -it ubuntu:20.04 bash      
root@e5fa6e953127:/# ls -l /usr/bin/mkdir
-rwxr-xr-x. 1 root root 88408 Sep  5  2019 /usr/bin/mkdir
root@e5fa6e953127:/# /usr/bin/mkdir --version
mkdir (GNU coreutils) 8.30
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
```

**Comment by sebastianMagnaldi** [comment] 2023-03-02 13:39
![image (24)](https://user-images.githubusercontent.com/96889640/222444589-641c0e36-168e-42f9-b007-06e52d2e35cd.png)

**Comment by tateeskew** [comment] 2023-03-02 14:15
It should be noted that upon updating from an earlier release of Ubuntu (18.04), certain binaries like `mkdir` continue to live in `/bin` and don't get moved to `/usr/bin`
The action doesn't take this into account and just assumes that anyone that is running Ubuntu 20.04 will have that binary in `/usr/bin` which is not the default if you've updated your system from an earlier LTS release for Ubuntu. I personally think the action should take this into account.

**Comment by dentarg** [comment] 2023-03-02 17:43
I don't think the action should. `setup-ruby` action is built for GitHub Actions. It is maintained by very few people and we should be super grateful that it even exist.

The README says

> This action might work with [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) if the [Runner Image](https://github.com/actions/runner-images) is very similar to the ones used by GitHub runners.

Yes, there's a list with pointers, but don't expect that list to be complete. Again, it is out of scope for this action to reliably work with self-hosted runners.

It is on you to make it work if you use this action with a self-hosted runner.

**Comment by eregon** [comment] 2023-03-02 19:53
@dentarg said it better than I could.

This action anyway cannot "take this into account".
When CRuby is built it captures the path of `mkdir` in `RbConfig::CONFIG["MKDIR_P"]`.
See https://github.com/eregon/setup-ruby-test/actions/runs/4317628218/jobs/7534925359

Ubuntu 18.05 only has /bin/mkdir, 20.04 and 22.04 have both /usr/bin/mkdir and /bin/mkdir.
As shown in the log above, it's also proof 20.04 has `mkdir` in both /usr/bin/mkdir and /bin/mkdir.

> It should be noted that upon updating from an earlier release of Ubuntu (18.04), certain binaries like mkdir continue to live in /bin and don't get moved to /usr/bin

Interesting, maybe this should be considered an Ubuntu update bug then? It's a significant difference from a fresh install.

If you use a self-hosted runner, you are responsible to maintain it.
This action only works on self-hosted runners if they are exactly the same as GitHub-hosted runner images, or if they have Ruby already in the hostedtoolcache, because the prebuilt CRuby binaries expect that and that cannot be changed realistically.

---

There is one general solution for self-hosted runners (and other arch than amd64, and other OS, etc) which would be to not reuse prebuilt Rubies built on GH-hosted runners but rather build it on the fly the first time with `ruby-build`. That's complicated because it would need to handle concurrent jobs trying to built it.
Something easier would be to just output a message telling people to use `ruby-build` to install in the runner hostedtoolcache, and then they are responsible for it.
What we really need for either of those is a reliable way to detect self-hosted vs not (I'm not aware of one).

Also, reactions like the above and #469 (and some other self-hosted runner issues) make me want to not spend a second more on that. People should realize it's not a bug of this action and stop asking to support nonsensical things or free help when they just have a self-hosted runner which is not properly setup or not similar enough to GitHub-hosted runners.

**Comment by eregon** [comment] 2023-03-02 20:02
Some more thoughts for today:
* Probably we should require issues to have a (public) reproduction on GitHub-hosted runners, and reject issues which only happen on self-hosted runners. And link to some better place for that in the issue templates, maybe https://github.com/orgs/community/discussions/categories/actions.
* Maybe we should prevent filing issues completely on this repo and just allow PRs. Maybe that would make people understand we don't owe them anything and what can and can't be solved in this action.

**Comment by hsbt** [comment] 2023-03-03 07:05
FYI: this problem caused by [UsrMerge](https://wiki.debian.org/UsrMerge) since 2021.
