### ISSUE TITLE
bundle installation fails with Ruby 2.5.1 and Bundler 2.1.4

### ISSUE THREAD

**Issue by njm506** [ruby/setup-ruby#122] opened 2020-12-09 13:09 UTC
I've hit a strange issue while using this action.  We're using mostly default options, with `bundler-cache: true` on an Ubuntu 18.04 image.  We use `.ruby-version` and `Gemfile.lock` and I can see from log output that the action picks up ruby 2.5.1 and bundler 2.1.4 correctly.

It successfully installs bundler 2.1.4 but the first `bundle config` command fails with `Can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)`.  This worked in July when I this was last touched.  The full log output is at the end of the message.

After some wrangling, I found that I could work around this by turning off the cache and instead appending the `bundle` commands manually in my actions file:
```
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
      - name: Install bundle manually
        run: |
          bundle config --local path vendor/bundle
          bundle config --local deployment true
          bundle install --jobs 4
      - name: Rubocop
        run: bundle exec rubocop
```
This works, so it seems somehow the `bundle` command isn't in a working state for the built-in `exec`s - could it be executing the wrong `bin` stub maybe?

The reported image is:
```
Operating System
  Ubuntu
  18.04.5
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20201129.1
```

The full output from one of the failing job (our rspec job does the same):
```
Downloading Ruby
  https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-2.5.1-ubuntu-18.04.tar.gz
  Took   0.46 seconds
Extracting Ruby
  /bin/tar -xz -C /opt/hostedtoolcache/Ruby/2.5.1 -f /home/runner/work/_temp/***********
  Took   0.32 seconds
Installing Bundler
  Using Bundler 2 from Gemfile.lock BUNDLED WITH 2.1.4
  /opt/hostedtoolcache/Ruby/2.5.1/x64/bin/gem install bundler -v ~> 2 --no-document
  Successfully installed bundler-2.1.4
  1 gem installed
  Took   0.56 seconds
bundle install
  /opt/hostedtoolcache/Ruby/2.5.1/x64/bin/bundle config --local path vendor/bundle
  /opt/hostedtoolcache/Ruby/2.5.1/x64/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
  	from /opt/hostedtoolcache/Ruby/2.5.1/x64/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
  	from /opt/hostedtoolcache/Ruby/2.5.1/x64/bin/bundle:23:in `<main>'
  Took   0.07 seconds
```

**Comment by eregon** [comment] 2020-12-09 15:30
Thanks for the report.

This error message sounds like some bug in the RubyGems shipped with Ruby 2.5.

It is probably due to https://github.com/ruby/setup-ruby/pull/120
So I think I'll try setting `BUNDLER_VERSION` only if needed (if `bundler: 1` and Ruby >= 2.7).

Do you have a Gemfile I could try to reproduce with and check that solves it?

**Comment by njm506** [comment] 2020-12-09 15:43
Thanks for the quick reply; I don't have a straightforward Gemfile as such (the action I hit this on is for an internal gem so it's using a gemspec) - however I have tested the action against the `ojab/setup-ruby@master` which is the source for #120 and I can verify that does fix it for me.

Hopefully that is enough information to consider this fixed in #120, but if not let me know and I'll see what I can do.

**Comment by eregon** [comment] 2020-12-09 15:49
Ah, so it might be already fixed?

Could you try a new run with `ruby/setup-ruby@v1`?

And could you also try `ruby/setup-ruby@bundler-version-when-needed` which only sets `BUNDLER_VERSION` when needed? It's probably safer anyway.

**Comment by njm506** [comment] 2020-12-09 15:58
I can confirm that (as of just now), `ruby/setup-ruby@v1` still fails as before, and that `ruby/setup-ruby@bundler-version-when-needed` passes :)

**Comment by eregon** [comment] 2020-12-09 16:13
Released as https://github.com/ruby/setup-ruby/releases/tag/v1.58.1, so `ruby/setup-ruby@v1` should work fine now.

**Closed by eregon** 2020-12-09 16:13 UTC
