### ISSUE TITLE
bin/bundle failed with exit code 18

### ISSUE THREAD

**Issue by frmsaul** [ruby/setup-ruby#456] opened 2023-01-30 23:34 UTC
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### The workflow code or a link to the workflow file

```yaml
I'm getting the following issue: 


Error: Error: The process '/opt/hostedtoolcache/Ruby/3.2.0-rc1/x64/bin/bundle' failed with exit code 18
    at ExecState._setResult (/home/runner/work/_actions/ruby/setup-ruby/ee2113536afb7f793eed4ce60e8d3b26db912da4/dist/index.js:5340:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/ruby/setup-ruby/ee2113536afb7f793eed4ce60e8d3b26db912da4/dist/index.js:5323:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ruby/setup-ruby/ee2113536afb7f793eed4ce60e8d3b26db912da4/dist/index.js:5217:27)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

The rails version i'm using is 3.2.0.
```


### Link to the log of a failed workflow job, or to a gist with the output

https://gist.github.com/frmsaul/6812eeea0f96e98bd80aa08e5bc73e5b

### The command and output of the failing step

```shell
Error: Error: The process '/opt/hostedtoolcache/Ruby/3.2.0-rc1/x64/bin/bundle' failed with exit code 18
    at ExecState._setResult (/home/runner/work/_actions/ruby/setup-ruby/ee2113536afb7f793eed4ce60e8d3b26db912da4/dist/index.js:5340:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/ruby/setup-ruby/ee2113536afb7f793eed4ce60e8d3b26db912da4/dist/index.js:5323:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ruby/setup-ruby/ee2113536afb7f793eed4ce60e8d3b26db912da4/dist/index.js:5217:27)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```
```


### Any other notes?

What would be a good way to learn what exit code 18 means? Couldn't find any mention of it in the bundler docs.

**Comment by wrburgess** [comment] 2023-01-31 22:33
I found that updating `gem "nokogiri", "1.14.0"` to `gem "nokogiri", "1.14.1"` appears to be the change causing this issue. The exit code changes from commit to commit, though.

**Comment by frmsaul** [comment] 2023-01-31 23:15
Hmm interesting. My repo doesn't use `nokogiri`, must be something similar.

**Comment by kadams54** [comment] 2023-02-04 03:16
FWIW, I'm also running into this issue with a brand new Rails app. No `nokogiri` and all the gems are updated. I've tried both Ruby 3.2.0 and 3.1.3, with the same results.

**Comment by al2o3cr** [comment] 2023-02-04 18:39
The POSIX name for error code 18 is `EXDEV`, "cross-device link not permitted". The usual cause is trying to rename files across device boundaries; Actions has experienced issues with this error [in the past](https://github.com/actions/runner-images/issues/922) but that ticket didn't have specifics about what was "reverted".

**Comment by fbuys** [comment] 2023-02-09 19:19
We had the same issue with this config:
```
- uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
```

Updating the the ruby version to `ruby-version: '3.2.0'` fixed it for us.

**Comment by eregon** [comment] 2023-02-10 01:08
You checked:
> I verified it reproduces with the latest version with - uses: ruby/setup-ruby@v1 (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

But you did not do it. In your log, 3.2.0-rc1 is picked because you use ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4.
So I close this, and you can open another one which respects the template.

**Closed by eregon** 2023-02-10 01:08 UTC

**Comment by wrburgess** [comment] 2023-02-10 23:56
@eregon I do understand why you want a process that "respects the template" but I can say I've tried to run Github Actions locally on my Mac M1 and there are bugs throughout. I don't have the expertise to make them run locally in order to submit bug reports on here.

I can also say that any attempt to upgrade ruby to 3.2.1 or certain gems fail to work with `setup-ruby` and the error code doesn't provide enough information to understand the problem.

I'm unable to debug this issue with the logs provided, unable to run GH Actions locally, and therefore unable to submit bug reports related to any of it due to this restriction.

**Comment by dentarg** [comment] 2023-02-11 00:02
the issue seems to be, bundler aborting because:

>Your Ruby version is 3.2.0.rc1, but your Gemfile specified 3.2.0

use the latest version of this action and it should work: `- uses: ruby/setup-ruby@v1`

**Comment by wrburgess** [comment] 2023-02-11 00:13
@dentarg I'm not getting further when making sure ruby version specifications are in sync:

```ruby
Run ruby/setup-ruby@v1
  with:
    bundler-cache: true
    ruby-version: 3.2.1
  env:
    RAILS_ENV: test
    ES_HOME: /home/runner/elasticsearch/8.6.1
  
Modifying PATH
  Entries added to PATH to use selected Ruby:
    /opt/hostedtoolcache/Ruby/[3](https://github.com/[org]/[repo]/actions/runs/4148669205/jobs/7176885042#step:6:3).2.1/x6[4](https://github.com/[org]/[repo]/actions/runs/4148669205/jobs/7176885042#step:6:4)/bin
Downloading Ruby
  https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-3.2.1-ubuntu-22.04.tar.gz
  Took   2.32 seconds
Extracting  Ruby
  /usr/bin/tar -xz -C /opt/hostedtoolcache/Ruby/3.2.1 -f /home/runner/work/_temp/cea[5](https://github.com/[org]/[repo]/actions/runs/4148669205/jobs/7176885042#step:6:5)e07b-0eb3-4f3f-ad17-b5b2114e07f[6](https://github.com/[org]/[repo]/actions/runs/4148669205/jobs/7176885042#step:6:6)
  Took   0.62 seconds
Print Ruby version
Installing Bundler
  Using Bundler 2.4.6 from Gemfile.lock BUNDLED WITH 2.4.6
  /opt/hostedtoolcache/Ruby/3.2.1/x64/bin/gem install bundler -v 2.4.6
  Successfully installed bundler-2.4.6
  1 gem installed
  Took   0.66 seconds
bundle install
  /opt/hostedtoolcache/Ruby/3.2.1/x64/bin/bundle config --local path /home/runner/work/[org]/[repo]/vendor/bundle
  /opt/hostedtoolcache/Ruby/3.2.1/x64/bin/bundle config --local deployment true
  Cache key: setup-ruby-bundler-cache-v4-ubuntu-22.04-ruby-3.2.1-Gemfile.lock-1a9[7](https://github.com/[org]/[repo]/actions/runs/4148669205/jobs/7176885042#step:6:7)a0639b3fc[8](https://github.com/[org]/[repo]/actions/runs/4148669205/jobs/7176885042#step:6:8)3f0be4145da3ba9c4bc66ce3ac7bca2c7635dae3d9abeb9cc2
  /opt/hostedtoolcache/Ruby/3.2.1/x64/bin/bundle install --jobs 4
  Could not find nokogiri-1.14.1-x[8](https://github.com/[org]/[repo]/actions/runs/4148669205/jobs/7176885042#step:6:9)6_64-linux in cached gems or installed locally
  Took   2.28 seconds
Error: Error: The process '/opt/hostedtoolcache/Ruby/3.2.1/x64/bin/bundle' failed with exit code 7
    at ExecState._setResult (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5381:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5364:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5258:27)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:10[9](https://github.com/[org]/[repo]/actions/runs/4148669205/jobs/7176885042#step:6:10)2:[16](https://github.com/[org]/[repo]/actions/runs/4148669205/jobs/7176885042#step:6:19))
    at Process.ChildProcess._handle.onexit (node:internal/child_process:[30](https://github.com/[org]/[repo]/actions/runs/4148669205/jobs/7176885042#step:6:36)2:5)
```

**Comment by wrburgess** [comment] 2023-02-11 00:31
These configurations, with `ruby 3.2.0` and `nokogiri 1.14.0` do run correctly:

```ruby
Run ruby/setup-ruby@v1
  with:
    bundler-cache: true
    ruby-version: 3.2.0
  env:
    RAILS_ENV: test
    ES_HOME: /home/runner/elasticsearch/8.6.1
  
Modifying PATH
  Entries added to PATH to use selected Ruby:
    /opt/hostedtoolcache/Ruby/.2.0/x6/bin
Downloading Ruby
  https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-3.2.0-ubuntu-22.04.tar.gz
  Took   1.83 seconds
Extracting  Ruby
  /usr/bin/tar -xz -C /opt/hostedtoolcache/Ruby/3.2.0 -f /home/runner/work/_temp/a3bee3-7f7-40b0-9040-ad04ef6031cc
  Took   0.7 seconds
Print Ruby version
  /opt/hostedtoolcache/Ruby/3.2.0/x64/bin/ruby --version
  ruby 3.2.0 (2022-12-25 revision a5208271) [x86_64-linux]
  Took   0.06 seconds
Installing Bundler
  Using Bundler 2.4.1 from Gemfile.lock BUNDLED WITH 2.4.1
  /opt/hostedtoolcache/Ruby/3.2.0/x64/bin/gem install bundler -v 2.4.1
  Successfully installed bundler-2.4.1
  1 gem installed
  Took   0.64 seconds
bundle install
  /opt/hostedtoolcache/Ruby/3.2.0/x64/bin/bundle config --local path /home/runner/work/avails_server/avails_server/vendor/bundle
  /opt/hostedtoolcache/Ruby/3.2.0/x64/bin/bundle config --local deployment true
  Cache key: setup-ruby-bundler-cache-v4-ubuntu-22.04-ruby-3.2.0-Gemfile.lock-1b5fcc65e8df18b9ca5f7e37833851f617e8b92a916b28e66a3fbb508014
  Received 0 of 68234792 (0.0%), 0.0 MBs/sec
  Received 4194304 of 68234792 (6.1%), 2.0 MBs/sec
  Received 68234792 of 68234792 (100.0%), 23.9 MBs/sec
  Cache Size: ~65 MB (68234792 B)
  /usr/bin/tar --use-compress-program unzstd -xf /home/runner/work/_temp/4f3c74aa-9fcb-4819-924a-0a6473bf5f33/cache.tzst -P -C /home/runner/work/avails_server/avails_server
  Cache restored successfully
  Found cache for key: setup-ruby-bundler-cache-v4-ubuntu-22.04-ruby-3.2.0-Gemfile.lock-f29711e55c7bf54abf793bb44250c4ba5fba6e010878596a9c4ec008
  /opt/hostedtoolcache/Ruby/3.2.0/x64/bin/bundle install --jobs 4

**Comment by MSP-Greg** [comment] 2023-02-11 00:54
@wrburgess

I wonder what issue the line from your log is showing, as `nokogiri-1.14.1-x6_64-linux` is not a valid name:
```
Could not find nokogiri-1.14.1-x6_64-linux in cached gems or installed locally
```

**Comment by wrburgess** [comment] 2023-02-11 01:03
@MSP-Greg I had to clean up the logs and I deleted a character. Here's the error, corrected:

`Could not find nokogiri-1.14.1-x86_64-linux in cached gems or installed locally`

**Comment by wrburgess** [comment] 2023-02-11 01:10
`Gemfile.lock` (abbreviated) configuration with the above failure(s). This is with a combo of ruby 3.2.0 and nokogiri 1.14.1

```
GEM
  nokogiri (1.14.1)
    mini_portile2 (~> 2.8.0)
    racc (~> 1.4)
  nokogiri (1.14.1-aarch64-linux)
    racc (~> 1.4)
  nokogiri (1.14.1-arm-linux)
    racc (~> 1.4)
  nokogiri (1.14.1-x86-linux)
    racc (~> 1.4)
  nokogiri (1.14.1-x86_64-darwin)
    racc (~> 1.4)
  nokogiri (1.14.1-x86_64-linux)
    racc (~> 1.4)

PLATFORMS
  linux
  ruby
  x86_64-darwin-22
  x86_64-linux
  
DEPENDENCIES
  rails (= 7.0.4.2)
  nokogiri (= 1.14.1)
  
RUBY VERSION
   ruby 3.2.0p0
   
BUNDLED WITH
   2.4.1
```

**Comment by MSP-Greg** [comment] 2023-02-11 01:21
Wondering if the issue is using the pre-compiled nokogiri gem?

**Comment by MSP-Greg** [comment] 2023-02-11 02:16
I installed Ruby 3.2.1 and installed nokogiri-1.14.1-x86_64-linux.  Didn't expect any issues, and had none.

As to setup-ruby, it's code is pretty simple, it just makes adjustments for versions.  Something is amiss with your code or the combination of versions that you're using.

**EDIT:** The only other option may be setting a new value for the cache version, which should be incremented if you feel the cache may be corrupt.  I'm not sure if that's what the issue is here:

```
Run ruby/setup-ruby@v1
  with:
    bundler-cache: true
    ruby-version: 3.2.1
    cache-version: 1
```

**Comment by wrburgess** [comment] 2023-02-11 02:17
After blowing away `vendor/cache`, rebuilding the Gemfile.lock, removing the `debug` gem altogether (no idea why it had issues) I can report that ruby 3.2.1 and nokogiri 1.14.1 are working.

I appreciate your efforts to reproduce the error and assist!

**Comment by eregon** [comment] 2023-02-11 10:10
> @eregon I do understand why you want a process that "respects the template" but I can say I've tried to run Github Actions locally on my Mac M1 and there are bugs throughout. I don't have the expertise to make them run locally in order to submit bug reports on here.

That's not what the template asks. The template asks you run the individual commands locally on your machine (like `bundle install`).

> I can also say that any attempt to upgrade ruby to 3.2.1 or certain gems fail to work with `setup-ruby` and the error code doesn't provide enough information to understand the problem.

There is the output of `bundle install` there, so if that's an issue, it's an issue of Bundler then.
The additional thing is setup-ruby groups output and you need to expand it or look at the full log.
That seems intuitive enough, but maybe we should no group the `bundle install` output, and also probably we shouldn't show the JS stacktrace because that's useless there and maybe confuses people thinking it's a setup-ruby issue when it's not.

> I'm unable to debug this issue with the logs provided, unable to run GH Actions locally, and therefore unable to submit bug reports related to any of it due to this restriction.

Then don't submit a bug report but ask in Discussions or on GitHub Actions' forums.

Also there is <1% chance this is a setup-ruby bug, you even found out that a different version of nokogiri solves the problem, so either a nokogiri, Bundler issue, or of course a bug in your workflow.
It could also be a bug in CRuby, in GHA runners or maybe in setup-ruby bundler caching.

I guess maybe we should update the template to suggest removing `bundler-cache: true` and see if that helps, if it does then it could be a setup-ruby bundler caching bug.

Thinking further, since this action only downloads a Ruby it built on GHA runners in a standard and tested way, and then runs `bundle install`, there is very little chance to be bugs there, but this kind of issue filed to the wrong place (or with not enough details) is annoying.
Maybe we should output GHA steps (a bunch of `- run: ...` on error to replace `uses: setup-ruby` and tell the user to run that, if it still repros, definitely not a bug of setup-ruby, if it doesn't then likely a bug of setup-ruby.
Also I'm thinking to require a public workflow and log, because it's more time consuming for maintainers to investigate if there is not a workflow run to investigate.

**Comment by eregon** [comment] 2023-02-11 10:13
Ah yes and of course using binary gems + RC versions of CRuby is most likely unsupported, so that's why I said https://github.com/ruby/setup-ruby/issues/456#issuecomment-1426505835 and it's unnaceptable to file an issue here but not even have time to try with `- uses: ruby/setup-ruby@v1` before filing it.

**Comment by eregon** [comment] 2023-02-11 10:23
And https://github.com/ruby/setup-ruby/issues/456#issuecomment-1426516810 is because your Gemfile.lock is out of sync with Gemfile. If you tried it locally with Ruby 3.2.1 you would find the same. You just need to `bundle install` locally with Ruby 3.2.1 and commit the changes. Or not specify the Ruby version in the Gemfile. This is not the place to teach people about Bundler though.

**Comment by eregon** [comment] 2023-02-11 13:07
I improved the output on error from Bundler, e.g. https://github.com/eregon/setup-ruby-test/actions/runs/4151423796/jobs/7181722160
