### ISSUE TITLE
sassc-ruby fails to install on Windows + JRuby

### ISSUE THREAD

**Issue by slonopotamus** [ruby/setup-ruby#81] opened 2020-08-25 11:51 UTC
See [test project](https://github.com/slonopotamus/sassc-jruby-test/blob/master/Gemfile) and [build log](https://github.com/slonopotamus/sassc-jruby-test/runs/1026295911?check_suite_focus=true#step:4:17).

I've also reported this bug as sass/sassc-ruby#214 because I'm not sure what party is to blame here.

**Comment by eregon** [comment] 2020-08-25 15:16
I'm pretty sure this is not an issue of setup-ruby, so I will close this.
But if after investigation it turns out it's something that can be improved in setup-ruby, happy to look at that.
I have very little experience with JRuby on Windows so I cannot help here.

I also replied on https://github.com/sass/sassc-ruby/issues/214.

**Comment by eregon** [comment] 2020-08-25 16:00
It seems this might be caused by sassc needing to have `cc`, etc in Path:https://github.com/sass/sassc-ruby/issues/214#issuecomment-680103438

@MSP-Greg I forgot, did you have some change to add MSSY2 to Path for JRuby too>

**Comment by MSP-Greg** [comment] 2020-08-25 16:22
@eregon

> I forgot, did you have some change to add MSYS2 to Path for JRuby too?

Ahh, I've also forgotten, but that sounds familiar.  I remember something with making the MSYS2 path globally available, maybe also for TruffleRuby?

Messy.  There's a few gems that compile a windows so/dll then use ffi/fiddle to access it.  That way, the compiled code isn't Ruby version specific since it doesn't access the Ruby dll's (like `x64-msvcrt-ruby280.dll`).

If these also work with JRuby, the MSYS2 path items would need to be added.

**Comment by slonopotamus** [comment] 2020-08-25 16:24
Do you know by chance _any_ native Ruby gem that builds successfully on JRuby + Windows + setup-ruby?

**Comment by MSP-Greg** [comment] 2020-08-25 16:39
@slonopotamus

I just forked your repo, added the MSYS2 path to the Build step, and JRuby installed sassc.  See:
https://github.com/MSP-Greg/sassc-jruby-test/runs/1027541219#step:4:19

So, it looks like we should be adding the MSYS2 path entries for any and all Windows Rubies.  Some CI also has scripts/bash commands, so it will also fix any possible issues with those...

**Comment by MSP-Greg** [comment] 2020-08-25 17:27
@eregon

The path change is part of #64, but rebasing is non-trivial.  I believe it will also change the default Windows bash shell to the MSYS2 shell, currently it's the Git shell.

I can work on it today...

**Comment by eregon** [comment] 2020-08-25 17:41
@MSP-Greg Might be easier to reapply the changes manually than rebasing.
In any case, it would be great to integrate the work from #64.

**Closed** 2020-09-03 10:13 UTC

**Comment by eregon** [comment] 2020-09-03 11:44
Fixed and released in https://github.com/ruby/setup-ruby/releases/tag/v1.45.0

**Comment by eregon** [comment] 2020-09-03 11:45
Thanks for the report!
