### ISSUE TITLE
Allow using bundler-cache: true without deployment

### ISSUE THREAD

**Issue by davidwessman** [ruby/setup-ruby#153] opened 2021-02-16 13:55 UTC
Hello!
I recently started updating my workflows to use the new `bundler-cache` option and it works great.
Then I ran into an error with this workflow where I update my Gemfile after setting up ruby.

<details>
  <summary>Github action workflow</summary>
  
```yaml
name: Update next

on:
  pull_request:
    paths:
      - "Gemfile.lock"

jobs:
  update:
    runs-on: ubuntu-20.04

    env:
      BUNDLE_GEMFILE: Gemfile.next

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.DUAL_BOOT_APP_ID }}
          private_key: ${{ secrets.DUAL_BOOT_PRIVATE_KEY }}

      - uses: actions/checkout@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Update Gemfile.next
        run: |
          bundle update --minor --conservative

      - uses: EndBug/add-and-commit@v7
        with:
          add: Gemfile.next.lock
          message: "Automatically bump next"
```

</details>

## Error

>You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.next.lock to version control.
If this is a development machine, remove the
/home/runner/work/uppstyrt/uppstyrt/Gemfile.next freeze
by running `bundle config --delete deployment`.

Would there be any way to use `bundler-cache: true` and be allowed to update Gemfile?
I tried adding `BUNDLER_DEPLOYMENT=false` but it did not make any difference.

**Comment by eregon** [comment] 2021-02-16 18:28
`--deployment` was automatically added in https://github.com/ruby/setup-ruby/pull/53.

In this case it seems a good reason to not want a frozen lockfile.

I think you can workaround with:
```
bundle config unset --local deployment
# or
bundle config set --local deployment false
```

**Comment by davidwessman** [comment] 2021-02-17 06:29
Thank you for your response!

The situation I have is that i have multiple lockfiles for the same Gemfile (as described by [fastruby.io](https://www.fastruby.io/blog/upgrade-rails/dual-boot/dual-boot-with-rails-6-0-beta.html)).
Our automatic dependency updates will make a PR for updating the normal Gemfile, but since we are running tests for dual-booting it fails unless the Gemfile.next.lock is updated as well.

When I run `ruby/setup-ruby` with `bundler-cache: true` in this situation I get an error.

<details>

<summary>Error message from `ruby/setup-ruby`</summary>

```sh
Using ruby-2.5.8 as input from file .ruby-version
Installing Bundler
  Using Bundler 1.17.3 from Gemfile.next.lock BUNDLED WITH 1.17.3
  /opt/hostedtoolcache/Ruby/2.5.8/x64/bin/gem install bundler -v 1.17.3 --no-document
  Successfully installed bundler-1.17.3
  1 gem installed
  Took   2.56 seconds
bundle install
  /opt/hostedtoolcache/Ruby/2.5.8/x64/bin/bundle config --local path /home/runner/work/app/app/vendor/bundle
  You are replacing the current local value of path, which is currently nil
  /opt/hostedtoolcache/Ruby/2.5.8/x64/bin/bundle config --local deployment true
  You are replacing the current local value of deployment, which is currently nil
  Cache key: setup-ruby-bundler-cache-v3-ubuntu-20.04-ruby-2.5.8-Gemfile.next.lock-ac22e5994e24261fd83f7ccaead9c6f6129893b43bc3415464d091e5aa411755
  Received 163577856 of 356186584 (45.9%), 154.0 MBs/sec
  Received 356186584 of 356186584 (100.0%), 168.0 MBs/sec
  Cache Size: ~340 MB (356186584 B)
  /usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/f5fa48f1-cd0b-4092-a630-2fc2b661290c/cache.tzst -P -C /home/runner/work/app/app
  Found cache for key: setup-ruby-bundler-cache-v3-ubuntu-20.04-ruby-2.5.8-Gemfile.next.lock-7c3c0335545e830737bf35708c3431bb34ce1c2b1a28ada2faecd0c6daff9c7f
  /opt/hostedtoolcache/Ruby/2.5.8/x64/bin/bundle install --jobs 4
  You are trying to install in deployment mode after changing
  your Gemfile. Run `bundle install` elsewhere and add the
  updated Gemfile.next.lock to version control.
  
  If this is a development machine, remove the
  /home/runner/work/application/application/Gemfile.next freeze
  by running `bundle config --delete deployment`.
  
  The dependencies in your gemfile changed
  
  You have added to the Gemfile:
  * blinka-reporter (~> 0.3.2)
  
  You have deleted from the Gemfile:
  * blinka-reporter (~> 0.3.3)
  Took  18.02 seconds
Error: The process '/opt/hostedtoolcache/Ruby/2.5.8/x64/bin/bundle' failed with exit code 16
```

</details>

Would it make sense to have it run without setting `deployment` at all?

**Comment by eregon** [comment] 2021-02-17 09:31
Ah of course, I forgot one cannot run `bundle config` commands in between.
Respecting the `BUNDLER_DEPLOYMENT` env var seems a good fix.

I'm trying to clarify in https://github.com/ruby/setup-ruby/pull/53#issuecomment-780034535 whether having `--depolyment` set by default is necessary/useful.

**Comment by eregon** [comment] 2021-02-18 16:29
@davidwessman Doesn't one of the commands in https://github.com/ruby/setup-ruby/issues/153#issuecomment-780032383 (doesn't matter which) work if you add it just before `bundle update --minor --conservative` in your workflow?

**Comment by scottjacobsen** [comment] 2021-02-19 01:23
I'm noticing a type-o in the env var you are using - it should be `BUNDLE_DEPLOYMENT=false`, not `BUNDLER_DEPLOYMENT`.

Per the bundler docs https://bundler.io/v2.2/man/bundle-config.1.html the ENV var should override the `bundle config deployment` that is set by this action because `bundle config deployment true` writes to the global `~/.bundle/config` file.

In my local testing

```shell
> bundle config deployment true
> bundle config
Settings are listed in order of priority. The top value will be used.
deployment
Set for the current user (/Users/scott/.bundle/config): true
> BUNDLE_DEPLOYMENT=false bundle config
Settings are listed in order of priority. The top value will be used
deployment
Set via BUNDLE_DEPLOYMENT: false
Set for the current user (/Users/scott/.bundle/config): true
```

I also confirmed `> bundle install` installs in deployment mode, while `> BUNDLE_DEPLOYMENT=false bundle` installs in "normal" non-deployment mode.

It may be worth updating this action to use `bundle config set --global deployment true` to make it clear?

**Comment by scottjacobsen** [comment] 2021-02-19 01:32
After some review I noticed this action does `bundle config set --local development true`, and not just `bundle config set development true` as I assumed. Unfortunately this appears to mean it will take priority over the ENV var. Is it required to use `--local`, or can `--global` be used? `--global` would be ideal because settings could then be overridden with ENV vars.

**Comment by davidwessman** [comment] 2021-02-19 06:17
@scottjacobsen Thank you for noticing the typo, will try again 🙂

**Comment by eregon** [comment] 2021-02-19 10:39
Global is not an option (and very rarely a good idea to use anyway for such settings), ruby/setup-ruby shouldn't affect how bundle how bundle works in general, only for the specific Gemfile is installs.

@davidwessman Please try https://github.com/ruby/setup-ruby/issues/153#issuecomment-781468294.
The env var won't work currently.

**Comment by scottjacobsen** [comment] 2021-02-19 17:17
Just curious why global is not an option? Is `~/.bundle/config` not writable? 

If there is no technical limitation to using global scope bundler is designed such that the global options have the lowest priority and there are two ways to override them (a local config file and env vars). Local has the highest priority and there is no clean way to override them. Global is exactly the right place to set system wide defaults because it allows specific projects to override defaults to meet their needs.

**Comment by eregon** [comment] 2021-02-20 14:27
It would likely break things and be unexpected if options such as the `path` and `deployment` are set globally.
For instance, if someone runs some bundle comment on a completely unrelated Gemfile, and used `ruby/setup-ruby` before for some other Gemfile, it would be affected by those settings, which would be very surprising.

**Comment by eregon** [comment] 2021-02-20 16:20
I looked into this, and I think disabling deployment is basically asking for troubles.
`ruby/setup-ruby` needs to hash the lockfile, and it assumes the lockfile matches the gemfile.
So if `bundle install` as done by this action fails when using `bundler-cache` true due to the deployment flag, then it means there is something wrong the checked in Gemfile.lock, and that's typically worth fixing.

If for other bundle commands after install you want to remove deployment, that's fine, just use `bundle config --local deployment false` after ruby/setup-ruby and before your `bundle` command needing to modify the Gemfile.

**Closed by eregon** 2021-02-20 16:20 UTC

**Comment by davidwessman** [comment] 2021-02-23 09:09
Thank you for investigating further.

It does however not work for my use-case since my Gemfiles are out of sync, which is what the job needs to fix.
I will have to do some manual caching 🙂

**Comment by viktorianer** [comment] 2023-02-26 21:28
I'm just trying to use `ruby-setup` with https://github.com/pivotal/LicenseFinder and have the issue, where I need to install all gems, to check their licenses, and bundler can not find gems:

```bash
Run ruby/setup-ruby@v1
> bundle install
Using nokogiri 1.14.1 (x86_64-linux)
...
Using google-protobuf 3.21.12 (x86_64-linux)
....

Run bin/license_finder --format text
/opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/bundler-2.4.1/lib/bundler/definition.rb:523:in `materialize': Could not find google-protobuf-3.21.12, nokogiri-1.14.1, mini_portile2-2.8.1 in locally installed gems (Bundler::GemNotFound)
```

I can not see `mini_portile2` been installed with `ruby-setup`, but `nokogiri` and `google-protobuf`.
The gem `mini_portile2` is dependency of `nokogiri`, with himself is dependency of a lot of different gems. Some of them in default group, some in development group, etc.

Is the `bundle config --local deployment true` is preventing the installation here?

If I remove `bundler-cache: true` and install gems with `run: bundle install`, it will work. But, now I have no cache feature.
 
```bash
Run bin/license_finder --format text #\
  bin/license_finder --format text
  shell: /usr/bin/bash -e {0}
  env:
    REVIEWDOG_GITHUB_API_TOKEN: ***
  
LicenseFinder::Bundler: is active
LicenseFinder::NPM: is active
LicenseFinder::Yarn: is active

Dependencies that need approval:
@rails/actioncable, 7.0.4, MIT
@rails/activestorage, 7.0.4, MIT
...
```

If `deployment true` is the issue here, then I would love to have the option to deactivate it.

**Comment by eregon** [comment] 2023-03-05 19:08
@viktorianer It seems unrelated. Or at least not a bug of this action, but of your usage and/or Bundler.
