### ISSUE TITLE
Add v1 tag

### ISSUE THREAD

**Issue by tadman** [ruby/setup-ruby#107] opened 2020-11-11 00:40 UTC
Due to a limitation in the [`act`](https://github.com/nektos/act/issues/234) tool, it'd be nice if there was a `v1` tag as well as a branch.

Right now it's necessary to pin down to a specific version in order to use `ruby/setup-ruby@...`

**Comment by eregon** [comment] 2020-11-11 12:21
Duplicate of #55.

Interestingly it seems allowed to have both a branch and tag of the same name, I find it very confusing though.

Anyway, I'm not moving tags, that's against the nature of tags of `git`.

**Closed by eregon** 2020-11-11 12:21 UTC

**Comment by eregon** [comment] 2020-11-11 12:45
FWIW https://github.com/actions/toolkit/pull/631

**Comment by tadman** [comment] 2020-11-12 22:25
Thanks for the clarification. This was less a complaint and more of a stub for other people with the same problem to find a solution. I couldn't find anything even after digging, so the link to #55 helps.
